### ISSUE TITLE
deprecated model of tensorflow

### ISSUE THREAD

**Issue by yani-rl-ai** [NilsDengler/sem_mapping#2]
hi can i run your tensorflow object detection in ros noetic?
because i found the tensorflow model is deprecated and is not compatible with python 3

**Comment by NilsDengler** [comment]
As already stated in the readme I just use the repository of osrf and a pretrained model from the tensorflow model zoo.  If they are not working anymore, I'm sure there are newer versions of both somewhere. However, since my approach does not rely on a specific object detection model itself, you can use any other model as well.
